platform:
  - x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'

install:
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - ps: Install-Product node 6 x64
  - yarn install

test_script:
  - yarn test

build_script:
  - set NODE_ENV=production
  - yarn ci-build

artifacts:
  - path: dist/*.exe

deploy:
  provider: Environment
  name: signal-desktop-builds
