platform:
  - x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'

install:
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - ps: Install-Product node 6 x64
  - yarn install

build_script:
  - yarn run generate
  - ./node_modules/.bin/build --em.environment=%SIGNAL_ENV% --publish=never

test_script:
  - ./node_modules/.bin/grunt test-release:win
  - yarn test

environment:
  SIGNAL_ENV: production

deploy:
  provider: S3
  access_key_id: AKIAJR7OQ5SVTFKPPLXQ
  secret_access_key: xl6I4z5jgUDdwG6MLTM3Kn1N1QpVKZvFrR72HTZbvh8yxyHfGX/aDxCHk/QCALXz
  bucket: signal-desktop-builds
  region: us-west-1
  folder: '%APPVEYOR_REPO_NAME%/%APPVEYOR_REPO_COMMIT%'
  artifact: dist/*.*
